apiVersion: "v1"
kind: "Service"
metadata:
  name: "webapp-deployment"
  namespace: "default"
  labels:
    app: "webapp"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: "webapp"
  type: "LoadBalancer"
  loadBalancerIP: ""
